### ISSUE TITLE
Why have you DEPRECATED Guided Filter Alpha?

### ISSUE THREAD

**Issue by niko2020** [spacepxl/ComfyUI-Image-Filters#7]
Hi,
Is there a better/updated node to use in place of Guided Filter Alpha?

Cheers & thanks

**Comment by niko2020** [comment]
sorry, found "GuidedFilterImage"

**Comment by spacepxl** [comment]
Right, you found the reason already. GuidedFilterImage should do all the same things, but if you find an issue that requires the old node, let me know. I deprecated instead of removing it to see if it caused any issues.
